### ISSUE TITLE
Git and GitHub training

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI/Training#1]
Users want to know how to use Git and GitHub to collaborate on ACCESS repositories.

The ACCESS NRI wants to put some specific rules and settings in place to help with the administration and safety of the repositories.

Can we rely on available training material or do we have to create our own?

**Comment by ccarouge** [comment]
We can probably rely on available material for Git training. For GitHub, we may want to write our own to introduce specific settings we'd like people to use.

**Comment by aidanheerdegen** [comment]
I think we want to use as much as possible provided by others. There is a lot out there for GitHub. Maybe collect some here and see what gaps need to be filled?

**Comment by aidanheerdegen** [comment]
Official GitHub quickstart guide

https://docs.github.com/en/get-started/quickstart

This is a nice step-by-step not assuming much introductory tutorial

https://codewithchris.com/github-tutorial/

I need to check out some of these GitHub extensions for VSCode!

https://code.visualstudio.com/docs/editor/github

**Comment by ccarouge** [comment]
[Git by Software Carpentries](https://swcarpentry.github.io/git-novice/index.html).
Pros:
 - easy to follow
 - includes setting SSH keys for GitHub
 - includes conflict resolution
 
 Cons:
  - no mention of branches
  - for GitHub, pushes to main
  - no notion of Pull Requests

**Comment by ccarouge** [comment]
> I need to check out some of these GitHub extensions for VSCode!
> 
> https://code.visualstudio.com/docs/editor/github

Github pull request and issues extension is great!

**Comment by ccarouge** [comment]
The Atlassian Git tutorials seem pretty good: https://www.atlassian.com/git/tutorials

Only possible downside is there seems to be a lot of explanations of how things work instead of just what command to use when.

**Comment by ccarouge** [comment]
This YouTube playlist is pretty cool: https://youtube.com/playlist?list=PLWKjhJtqVAbkFiqHnNaxpOPhh9tSWMXIF 

In particular this video is a good summary of the workflow based on the commands: https://youtu.be/bbanTh2CoAY

**Comment by ccarouge** [comment]
Great Cheatsheet for SVN users moving to Git: https://www.git-tower.com/blog/git-for-subversion-users-cheat-sheet/

**Comment by ccarouge** [comment]
Review instructions: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request : general instructions
https://haacked.com/archive/2019/06/03/suggested-changes/ : nice example of adding direct code suggestions
